### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by ApsaraGeek** [BBVA/SALD#3]
~/myprojects/anomalydetection/Tarkin$ ./check-docker.sh 

real	0m15.783s
user	0m0.012s
sys	0m0.005s
**./check-docker.sh: line 18: jq: command not found**

# Total logs in input file:
20
# Infrequent logs:
3
# Distressing logs:
3
When I run the next script I cant see any sentiment score:
~/myprojects/anomalydetection/Tarkin$ ./check-demo-docker.sh 
**{"surprise": 1, "sentiment_score": 0}**

real	0m8.645s
user	0m0.017s
sys	0m0.000s

 Docker version 17.12.0-ce, build c97c6d6
Ubuntu version 17.10

**Comment by CesarGallego** [comment]
## ./check-docker.sh
Yes, you need jq to show better the results.
Follow instructions in https://stedolan.github.io/jq/download/

And you need pass the data file url Tarkin/data/input-logs-example-file.csv. Example:
./check-docker.sh Tarkin/data/input-logs-example-file.csv

## ./check-demo-docker.sh
check-demo-docker.sh expect a message to score. Example:
./check-demo-docker.sh "Good things"

I'll review the Readme regarding this issues. Thank you very much.

**Comment by ApsaraGeek** [comment]
Thanks a lot guys for the support. 
I have a query regarding the input log data. 
How to feed my own log data? Should all the columns in the csv file be specified?, where should I change the data?
And how to know which part of the log is found as an anomaly?

**Comment by CesarGallego** [comment]
You can pass your own data on check.sh line 19:

`time cat $CHECK_INPUT_FILE | python Tarkin/service/check.py > $CHECK_OUTPUT_FILE`

Just set the environment variable CHECK_INPUT_FILE to your csv data.

If you have another columns you must change the list in:
- Tarkin/service/check.py:36
- Tarkin/service/train.py:31
And check on those lines that you keep the msg field.

When Tarkin dectect an anomaly it'll be printed, normal lines will ignored by Tarkin. If you also need the msg just modify the line Tarkin/service/check.py:79 to print out.

We still working on be more use friendly, thank you very much for your help.
